/* ─────────────────────────────────────────────
 *  Mock Products Data
 *  Replace this with API call:
 *    const res = await fetch('/api/products');
 *    const products = await res.json();
 * ───────────────────────────────────────────── */

import { Product } from "./types";

/**
 * Image base path — all collection images live under /images/collections/
 * When migrating to a backend, replace these with CDN/cloud URLs.
 */
const IMG = "/images/collections";

export const products: Product[] = [
  {
    id: 1,
    name: "Kanjivaram Silk Saree",
    slug: "kanjivaram-silk-saree",
    image: `${IMG}/kanjivaram-silk.png`,
    price: 245,
    originalPrice: 390,
    rating: 5,
    reviews: 42,
    category: "Silk Sarees",
    badge: "New",
    description:
      "Luxurious golden Kanjivaram silk saree with rich zari work, perfect for weddings and festive occasions.",
    fabric: "Pure Silk",
    color: "Gold",
    inStock: true,
    createdAt: "2026-05-01",
  },
  {
    id: 2,
    name: "Bridal Red Banarasi",
    slug: "bridal-red-banarasi",
    image: `${IMG}/bridal-banarasi.png`,
    price: 520,
    rating: 4.5,
    reviews: 128,
    category: "Bridal",
    description:
      "Stunning bridal red Banarasi silk saree with intricate gold zari brocade, a timeless wedding essential.",
    fabric: "Banarasi Silk",
    color: "Red",
    inStock: true,
    createdAt: "2026-04-15",
  },
  {
    id: 3,
    name: "Pastel Chanderi Cotton",
    slug: "pastel-chanderi-cotton",
    image: `${IMG}/chanderi-cotton.png`,
    price: 110,
    originalPrice: 180,
    rating: 4,
    reviews: 88,
    category: "Cotton Sarees",
    badge: "-15%",
    description:
      "Elegant pastel pink Chanderi cotton saree with delicate silver border, ideal for office and casual wear.",
    fabric: "Chanderi Cotton",
    color: "Pastel Pink",
    inStock: true,
    createdAt: "2026-04-20",
  },
  {
    id: 4,
    name: "Emerald Georgette",
    slug: "emerald-georgette",
    image: `${IMG}/emerald-georgette.png`,
    price: 185,
    rating: 4.5,
    reviews: 89,
    category: "Handloom",
    description:
      "Rich emerald green Georgette saree with gold embroidery border, a stunning pick for evening events.",
    fabric: "Georgette",
    color: "Emerald Green",
    inStock: true,
    createdAt: "2026-04-10",
  },
  {
    id: 5,
    name: "Tussar Silk Heritage",
    slug: "tussar-silk-heritage",
    image: `${IMG}/tussar-silk.png`,
    price: 320,
    originalPrice: 450,
    rating: 5,
    reviews: 64,
    category: "Silk Sarees",
    badge: "Best Seller",
    description:
      "Beautiful tussar silk saree in beige and gold tones with traditional Madhubani-inspired prints.",
    fabric: "Tussar Silk",
    color: "Beige Gold",
    inStock: true,
    createdAt: "2026-03-25",
  },
  {
    id: 6,
    name: "Royal Banarasi Brocade",
    slug: "royal-banarasi-brocade",
    image: `${IMG}/bridal-banarasi.png`,
    price: 680,
    rating: 5,
    reviews: 156,
    category: "Bridal",
    description:
      "Premium royal Banarasi brocade saree with heavy gold zari throughout, a statement piece for grand celebrations.",
    fabric: "Banarasi Silk",
    color: "Deep Red",
    inStock: true,
    createdAt: "2026-03-20",
  },
  {
    id: 7,
    name: "Soft Cotton Handloom",
    slug: "soft-cotton-handloom",
    image: `${IMG}/chanderi-cotton.png`,
    price: 95,
    originalPrice: 140,
    rating: 4,
    reviews: 73,
    category: "Cotton Sarees",
    description:
      "Soft handloom cotton saree with gentle weave patterns, perfect for everyday elegance and comfort.",
    fabric: "Cotton",
    color: "Light Pink",
    inStock: true,
    createdAt: "2026-04-05",
  },
  {
    id: 8,
    name: "Pure Silk Kanjivaram",
    slug: "pure-silk-kanjivaram",
    image: `${IMG}/kanjivaram-silk.png`,
    price: 410,
    rating: 4.5,
    reviews: 102,
    category: "Silk Sarees",
    description:
      "Authentic pure silk Kanjivaram with temple border motifs, hand-woven by master artisans of Kanchipuram.",
    fabric: "Pure Silk",
    color: "Gold",
    inStock: true,
    createdAt: "2026-03-15",
  },
  {
    id: 9,
    name: "Designer Georgette Party",
    slug: "designer-georgette-party",
    image: `${IMG}/emerald-georgette.png`,
    price: 210,
    originalPrice: 290,
    rating: 4,
    reviews: 55,
    category: "Daily Wear",
    badge: "-28%",
    description:
      "Contemporary designer Georgette saree with modern prints, a versatile choice for parties and gatherings.",
    fabric: "Georgette",
    color: "Green",
    inStock: true,
    createdAt: "2026-04-25",
  },
  {
    id: 10,
    name: "Golden Tussar Weave",
    slug: "golden-tussar-weave",
    image: `${IMG}/tussar-silk.png`,
    price: 275,
    rating: 4.5,
    reviews: 47,
    category: "Handloom",
    description:
      "Handloom Tussar silk with golden weave patterns, a heritage piece showcasing traditional craftsmanship.",
    fabric: "Tussar Silk",
    color: "Golden Beige",
    inStock: true,
    createdAt: "2026-04-12",
  },
  {
    id: 11,
    name: "Festive Red Banarasi",
    slug: "festive-red-banarasi",
    image: `${IMG}/bridal-banarasi.png`,
    price: 550,
    originalPrice: 720,
    rating: 5,
    reviews: 91,
    category: "Bridal",
    badge: "Trending",
    description:
      "Festive red Banarasi saree with intricate gold motifs, a crowd favorite for weddings and celebrations.",
    fabric: "Banarasi Silk",
    color: "Red",
    inStock: true,
    createdAt: "2026-05-05",
  },
  {
    id: 12,
    name: "Daily Comfort Cotton",
    slug: "daily-comfort-cotton",
    image: `${IMG}/chanderi-cotton.png`,
    price: 75,
    rating: 4,
    reviews: 134,
    category: "Daily Wear",
    description:
      "Lightweight cotton saree for daily comfort, easy to drape with a soft finish for all-day wear.",
    fabric: "Cotton",
    color: "Pastel",
    inStock: true,
    createdAt: "2026-04-28",
  },
];
